
CREATE TABLE borrowed
(
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES users(id),
    book_id integer NOT NULL REFERENCES book(id),
    date date not null,
    primary key(id, date)
) PARTITION BY RANGE (date);


--Partition
CREATE TABLE public.borrowed_m01 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-01-01') TO ('2022-02-01');

CREATE TABLE public.borrowed_m02 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-02-01') TO ('2022-03-01');

CREATE TABLE public.borrowed_m03 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-03-01') TO ('2022-04-01');

CREATE TABLE public.borrowed_m04 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-04-01') TO ('2022-05-01');

CREATE TABLE public.borrowed_m05 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-05-01') TO ('2022-06-01');

CREATE TABLE public.borrowed_m06 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-06-01') TO ('2022-07-01');

CREATE TABLE public.borrowed_m07 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-07-01') TO ('2022-08-01');

CREATE TABLE public.borrowed_m08 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-08-01') TO ('2022-09-01');

CREATE TABLE public.borrowed_m09 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-09-01') TO ('2022-10-01');

CREATE TABLE public.borrowed_m10 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-10-01') TO ('2022-11-01');

CREATE TABLE public.borrowed_m11 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-11-01') TO ('2022-12-01');

CREATE TABLE public.borrowed_m12 PARTITION OF public.borrowed
    FOR VALUES FROM ('2022-12-01') TO ('2023-01-01');

--Index
CREATE INDEX ON borrowed (book_id);